# Generated by Django 4.2.5 on 2023-11-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebook',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='цена'),
        ),
    ]
